version: '3.3'
services:
  convertedconversion-ms:
    image: convertedcurrency/microservice
 
    ports:
      - "8082:8082"
    networks:
      - bootcamp-network
    depends_on:
      - eureka-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
  currencyconverter-ms:
    image: currencyconverter/microservice
  
    ports:
      - "8081:8081"
    networks:
      - bootcamp-network
    depends_on:
      - eureka-server
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://eureka-server:8761/eureka
  eureka-server:
    image: discovery/microservice
  
    ports:
      - "8761:8761"
    networks:
      - bootcamp-network
networks:
  bootcamp-network: